### ISSUE TITLE
Issue: Currently Crushing on Hannah

### ISSUE THREAD

**Issue by AndrewKhans** [limh0228/StardewSaves#3]

**Comment by limh0228** [comment]
What happened 21 hours ago??

**Comment by AndrewKhans** [comment]
This issue has been resolved. Do not re-open.

Best,
AndrewKhans

**Comment by limh0228** [comment]
I am sad to hear it is resolved :(

**Comment by AndrewKhans** [comment]
3/8/2021 Update: This issue persists. Assigning @limh0228 to work on resolving it.
